"use client";
import { useEffect, useMemo, useState } from "react";
import { Building2, CheckCircle2, FileText, Film, Image as ImageIcon, Landmark, LoaderCircle, MapPin, Plus, Save, Search, ShieldCheck, Trash2, UploadCloud, X } from "lucide-react";

const blank={name:"",code:"",developer:"",legal_name:"",project_type:"Căn hộ",status:"DRAFT",visibility:"PUBLIC",province:"",district:"",address:"",latitude:"",longitude:"",price_from:"",price_to:"",legal_status:"",progress:"",summary:"",description:"",amenities:[],featured:false,project_facts:{},legal_checklist:[],progress_timeline:[],ai_profile:{}};
const legalDefaults=["Quyết định chủ trương đầu tư","Quy hoạch chi tiết 1/500","Giấy phép xây dựng","Văn bản đủ điều kiện bán","Bảo lãnh ngân hàng","Giấy chứng nhận quyền sử dụng đất","Biên bản nghiệm thu"];
const tabs=[['overview','Tổng quan'],['images','Hình ảnh'],['videos','Video'],['documents','PDF & tài liệu'],['legal','Pháp lý'],['land','Sổ đỏ / Sổ hồng'],['progress','Tiến độ'],['map','Bản đồ'],['ai','AI dữ liệu']];
const money=v=>v?new Intl.NumberFormat("vi-VN").format(Number(v))+" ₫":"—";

export default function ProjectAdmin(){
 const [projects,setProjects]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(blank),[detail,setDetail]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[q,setQ]=useState(""),[tab,setTab]=useState('overview');
 const filtered=useMemo(()=>projects.filter(p=>(p.name+" "+(p.developer||"")+" "+(p.province||"")).toLowerCase().includes(q.toLowerCase())),[projects,q]);
 async function load(){setLoading(true);const d=await fetch("/api/admin/projects").then(r=>r.json());setProjects(d.projects||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function openProject(p){setSelected(p.id);const d=await fetch(`/api/admin/projects/${p.id}`).then(r=>r.json());setDetail(d);setForm({...blank,...d.project,project_facts:d.project.project_facts||{},legal_checklist:d.project.legal_checklist||[],progress_timeline:d.project.progress_timeline||[],ai_profile:d.project.ai_profile||{}});setTab('overview')}
 function newProject(){setSelected("new");setDetail({media:[],documents:[],landCertificates:[]});setForm(blank);setTab('overview')}
 async function save(e){e?.preventDefault();setSaving(true);setMsg("");const url=selected==="new"?"/api/admin/projects":`/api/admin/projects/${selected}`;const method=selected==="new"?"POST":"PATCH";const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,price_from:form.price_from||null,price_to:form.price_to||null,latitude:form.latitude||null,longitude:form.longitude||null})});const d=await r.json();setSaving(false);if(!r.ok){setMsg(d.error||"Không thể lưu");return}setMsg("Đã lưu dự án");await load();await openProject(d.project)}
 async function remove(){if(!confirm("Ẩn dự án này khỏi hệ thống?"))return;await fetch(`/api/admin/projects/${selected}`,{method:"DELETE"});setSelected(null);setDetail(null);setForm(blank);await load()}
 async function upload(kind,file,title="",isHero=false,category="OTHER",visibility="PUBLIC",notes=""){if(!file||selected==="new"){setMsg(selected==="new"?"Hãy lưu dự án trước khi tải tệp":"Chưa chọn tệp");return}setMsg("Đang tải tệp...");const fd=new FormData();fd.append("file",file);fd.append("kind",kind);fd.append("title",title);fd.append("isHero",String(isHero));fd.append("category",category);fd.append("visibility",visibility);fd.append("notes",notes);const r=await fetch(`/api/admin/projects/${selected}/media`,{method:"POST",body:fd});const d=await r.json();setMsg(r.ok?"Tải lên thành công":d.error||"Tải lên thất bại");if(r.ok)await openProject({id:selected})}
 async function addLandCertificate(payload,file){if(selected==='new'){setMsg('Hãy lưu dự án trước');return}const fd=new FormData();Object.entries(payload).forEach(([k,v])=>fd.append(k,v??''));if(file)fd.append('file',file);const r=await fetch(`/api/admin/projects/${selected}/land-certificates`,{method:'POST',body:fd});const d=await r.json();setMsg(r.ok?'Đã lưu hồ sơ sổ đỏ/sổ hồng':d.error||'Không thể lưu');if(r.ok)await openProject({id:selected})}
 const completion=useMemo(()=>{const checks=[form.name,form.developer,form.province,form.address,form.summary,form.description,detail?.media?.length,detail?.documents?.length,form.legal_checklist?.length,form.progress_timeline?.length];return Math.round(checks.filter(Boolean).length/checks.length*100)},[form,detail]);
 return <div className="v8AdminGrid">
  <section className="v8ProjectList"><div className="v8ListHead"><div><span className="v8Eyebrow">V8.0 PROJECT ADMIN</span><h2>Quản lý dự án</h2></div><button className="v8Primary" onClick={newProject}><Plus size={17}/>Tạo dự án</button></div><div className="v8Search"><Search size={17}/><input placeholder="Tìm dự án, chủ đầu tư..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="v8ProjectRows">{loading?<div className="v8Empty"><LoaderCircle className="spin"/>Đang tải dữ liệu...</div>:filtered.length?filtered.map(p=><button key={p.id} className={`v8ProjectRow ${selected===p.id?"active":""}`} onClick={()=>openProject(p)}><div className="v8Thumb">{p.hero_url?<img src={p.hero_url} alt=""/>:<Building2/>}</div><div><b>{p.name}</b><span>{p.developer||"Chưa có chủ đầu tư"}</span><small>{p.district||p.province||"Chưa cập nhật vị trí"}</small></div><aside><em className={`status ${String(p.status).toLowerCase()}`}>{p.status}</em><small>{p.media_count||0} media · {p.document_count||0} tài liệu</small></aside></button>):<div className="v8Empty">Chưa có dự án. Bấm “Tạo dự án”.</div>}</div></section>
  <section className="v8Editor">{!selected?<div className="v8Welcome"><Building2 size={44}/><h2>Project Digital Passport</h2><p>Chọn một dự án hoặc tạo mới để quản lý hồ sơ số, ảnh, video, PDF, pháp lý và sổ đỏ/sổ hồng.</p></div>:<><div className="v8EditorHead"><div><span className="v8Eyebrow">HỒ SƠ SỐ DỰ ÁN</span><h2>{selected==="new"?"Tạo dự án mới":form.name}</h2><div className="v8Completion"><span style={{width:`${completion}%`}}/><small>Hoàn thiện hồ sơ {completion}%</small></div></div><div className="v8HeadActions">{selected!=="new"&&<a href={`/du-an/${form.slug}`} target="_blank">Xem trước</a>}{selected!=="new"&&<button className="v8Danger" onClick={remove}><Trash2 size={16}/></button>}</div></div>{msg&&<div className="v8Notice">{msg}<button onClick={()=>setMsg("")}><X size={14}/></button></div>}
   <div className="v8Tabs">{tabs.map(([k,t])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{t}</button>)}</div>
   <form className="v8Form" onSubmit={save}>
    {tab==='overview'&&<Overview form={form} setForm={setForm}/>} 
    {tab==='images'&&<MediaTab title="Hình ảnh dự án" icon={<ImageIcon/>} accept="image/*" kind="IMAGE" media={(detail?.media||[]).filter(x=>x.media_type==='IMAGE')} upload={upload} hero/>}
    {tab==='videos'&&<MediaTab title="Video dự án" icon={<Film/>} accept="video/mp4,video/webm,video/quicktime" kind="VIDEO" media={(detail?.media||[]).filter(x=>x.media_type==='VIDEO')} upload={upload}/>} 
    {tab==='documents'&&<DocumentTab documents={detail?.documents||[]} upload={upload}/>} 
    {tab==='legal'&&<LegalTab form={form} setForm={setForm} upload={upload}/>} 
    {tab==='land'&&<LandTab certificates={detail?.landCertificates||[]} onSave={addLandCertificate}/>} 
    {tab==='progress'&&<ProgressTab form={form} setForm={setForm}/>} 
    {tab==='map'&&<MapTab form={form} setForm={setForm}/>} 
    {tab==='ai'&&<AiTab form={form} setForm={setForm}/>} 
    <div className="v8SaveBar"><label className="v8Check"><input type="checkbox" checked={!!form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/>Dự án nổi bật</label><div><button type="button" onClick={()=>setForm({...form,status:'DRAFT'})}>Lưu nháp</button><button className="v8Primary" disabled={saving}>{saving?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>}Lưu thay đổi</button></div></div>
   </form></>}</section>
 </div>
}

function Overview({form,setForm}){const facts=form.project_facts||{};return <><Section title="Thông tin cơ bản"><Fields><L t="Tên dự án"><input required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></L><L t="Mã dự án"><input value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})}/></L><L t="Tên pháp lý"><input value={form.legal_name||''} onChange={e=>setForm({...form,legal_name:e.target.value})}/></L><L t="Chủ đầu tư"><input value={form.developer||''} onChange={e=>setForm({...form,developer:e.target.value})}/></L><L t="Loại hình"><select value={form.project_type||''} onChange={e=>setForm({...form,project_type:e.target.value})}>{['Căn hộ','Nhà phố','Biệt thự','Đất nền','Thương mại','Khu đô thị'].map(x=><option key={x}>{x}</option>)}</select></L><L t="Trạng thái"><select value={form.status||'DRAFT'} onChange={e=>setForm({...form,status:e.target.value})}><option value="DRAFT">Bản nháp</option><option value="REVIEW">Chờ kiểm duyệt</option><option value="APPROVED">Đã duyệt</option><option value="PUBLISHED">Đã xuất bản</option><option value="HIDDEN">Tạm ẩn</option></select></L><L t="Quyền xem"><select value={form.visibility||'PUBLIC'} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="PUBLIC">Công khai</option><option value="INTERNAL">Nội bộ</option><option value="PRIVATE">Bảo mật</option></select></L></Fields></Section><Section title="Vị trí và giá"><Fields><L t="Tỉnh/Thành"><input value={form.province||''} onChange={e=>setForm({...form,province:e.target.value})}/></L><L t="Quận/Huyện"><input value={form.district||''} onChange={e=>setForm({...form,district:e.target.value})}/></L><L t="Địa chỉ" wide><input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></L><L t="Giá từ"><input type="number" value={form.price_from||''} onChange={e=>setForm({...form,price_from:e.target.value})}/><small>{money(form.price_from)}</small></L><L t="Giá đến"><input type="number" value={form.price_to||''} onChange={e=>setForm({...form,price_to:e.target.value})}/><small>{money(form.price_to)}</small></L></Fields></Section><Section title="Thông số dự án"><Fields>{[['total_area','Tổng diện tích'],['construction_density','Mật độ xây dựng'],['blocks','Số block'],['floors','Số tầng'],['units','Số lượng sản phẩm'],['handover','Thời gian bàn giao'],['ownership','Hình thức sở hữu'],['management_fee','Phí quản lý'],['guarantee_bank','Ngân hàng bảo lãnh'],['hotline','Hotline dự án']].map(([k,t])=><L key={k} t={t}><input value={facts[k]||''} onChange={e=>setForm({...form,project_facts:{...facts,[k]:e.target.value}})}/></L>)}</Fields></Section><Section title="Nội dung"><Fields one><L t="Tóm tắt"><textarea rows="3" value={form.summary||''} onChange={e=>setForm({...form,summary:e.target.value})}/></L><L t="Mô tả chi tiết"><textarea rows="7" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></L></Fields></Section></>}
function MediaTab({title,icon,accept,kind,media,upload,hero}){return <Section title={title}><UploadCard icon={icon} title={`Tải ${title.toLowerCase()}`} accept={accept} onUpload={(f,t,h)=>upload(kind,f,t,h)} hero={hero}/><div className="v8MediaGrid">{media.map(m=><article key={m.id}>{m.media_type==='VIDEO'?<video src={m.url} controls/>:<img src={m.url} alt=""/>}<b>{m.title||m.media_type}</b><span>{m.is_hero?'Hero · ':''}{m.visibility}</span></article>)}{!media.length&&<p>Chưa có dữ liệu.</p>}</div></Section>}
function DocumentTab({documents,upload}){return <Section title="Tài liệu PDF và phiên bản"><UploadCard icon={<FileText/>} title="Tải tài liệu PDF" accept="application/pdf" onUpload={(f,t)=>upload('DOCUMENT',f,t,false,'OTHER','INTERNAL')}/><div className="v8Docs">{documents.map(d=><a key={d.id} href={d.versions?.[0]?.file_url} target="_blank"><FileText/><span><b>{d.title}</b><small>{d.category} · phiên bản {d.current_version} · {d.visibility}</small></span></a>)}{!documents.length&&<p>Chưa có tài liệu.</p>}</div></Section>}
function LegalTab({form,setForm,upload}){const list=form.legal_checklist?.length?form.legal_checklist:legalDefaults.map(name=>({name,status:'MISSING',document_no:'',issued_by:'',issued_date:'',note:''}));const update=(i,k,v)=>{const n=[...list];n[i]={...n[i],[k]:v};setForm({...form,legal_checklist:n})};return <Section title="Checklist hồ sơ pháp lý"><div className="v8LegalList">{list.map((x,i)=><article key={i}><div className="v8LegalTitle"><ShieldCheck/><b>{x.name}</b><select value={x.status} onChange={e=>update(i,'status',e.target.value)}><option value="MISSING">Chưa có</option><option value="VERIFYING">Đang xác minh</option><option value="VALID">Hợp lệ</option><option value="NEED_MORE">Cần bổ sung</option></select></div><Fields><L t="Số văn bản"><input value={x.document_no||''} onChange={e=>update(i,'document_no',e.target.value)}/></L><L t="Cơ quan cấp"><input value={x.issued_by||''} onChange={e=>update(i,'issued_by',e.target.value)}/></L><L t="Ngày cấp"><input type="date" value={x.issued_date||''} onChange={e=>update(i,'issued_date',e.target.value)}/></L><L t="Ghi chú"><input value={x.note||''} onChange={e=>update(i,'note',e.target.value)}/></L></Fields></article>)}</div><UploadCard icon={<FileText/>} title="Đính kèm hồ sơ pháp lý" accept="application/pdf,image/*" onUpload={(f,t)=>upload('DOCUMENT',f,t,false,'LEGAL','PRIVATE')}/></Section>}
function LandTab({certificates,onSave}){const [data,setData]=useState({certificate_type:'Sổ hồng',certificate_no:'',book_no:'',parcel_no:'',map_sheet_no:'',area:'',land_use_type:'',use_term:'',owner_name:'',issued_by:'',issued_date:'',property_address:'',verification_status:'UNVERIFIED',visibility:'PRIVATE',notes:''}),[file,setFile]=useState(null);return <Section title="Sổ đỏ / Sổ hồng"><div className="v8SecurityNote"><Landmark/><div><b>Tài liệu bảo mật cao</b><span>Bản gốc chỉ dành cho Admin/Super Admin. Bản công khai phải che dữ liệu cá nhân, mã QR, chữ ký và số seri nhạy cảm.</span></div></div><Fields>{Object.entries({certificate_type:'Loại giấy chứng nhận',certificate_no:'Số phát hành',book_no:'Số vào sổ',parcel_no:'Số thửa',map_sheet_no:'Tờ bản đồ',area:'Diện tích',land_use_type:'Loại đất',use_term:'Thời hạn sử dụng',owner_name:'Người đứng tên',issued_by:'Cơ quan cấp',issued_date:'Ngày cấp',property_address:'Địa chỉ thửa đất'}).map(([k,t])=><L key={k} t={t}>{k==='issued_date'?<input type="date" value={data[k]} onChange={e=>setData({...data,[k]:e.target.value})}/>:<input value={data[k]} onChange={e=>setData({...data,[k]:e.target.value})}/>}</L>)}<L t="Trạng thái xác minh"><select value={data.verification_status} onChange={e=>setData({...data,verification_status:e.target.value})}><option value="UNVERIFIED">Chưa kiểm tra</option><option value="VERIFYING">Đang xác minh</option><option value="ORIGINAL_MATCHED">Đã đối chiếu bản gốc</option><option value="NEED_MORE">Cần bổ sung</option><option value="INVALID">Không hợp lệ</option></select></L><L t="Quyền xem"><select value={data.visibility} onChange={e=>setData({...data,visibility:e.target.value})}><option value="PRIVATE">Bảo mật cao</option><option value="INTERNAL">Nội bộ</option><option value="REDACTED_PUBLIC">Công khai bản che thông tin</option></select></L><L t="File scan" wide><input type="file" accept="application/pdf,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></L><L t="Ghi chú" wide><textarea rows="3" value={data.notes} onChange={e=>setData({...data,notes:e.target.value})}/></L></Fields><button type="button" className="v8Primary" onClick={()=>onSave(data,file)}><UploadCloud size={17}/>Lưu hồ sơ sổ đỏ/sổ hồng</button><div className="v8CertificateList">{certificates.map(c=><article key={c.id}><b>{c.certificate_type} · {c.certificate_no||'Chưa có số'}</b><span>Thửa {c.parcel_no||'—'} · Tờ {c.map_sheet_no||'—'} · {c.area||'—'} m²</span><small>{c.verification_status} · {c.visibility}</small></article>)}</div></Section>}
function ProgressTab({form,setForm}){const list=form.progress_timeline||[];const add=()=>setForm({...form,progress_timeline:[...list,{date:'',stage:'',percent:0,description:''}]});const up=(i,k,v)=>{const n=[...list];n[i]={...n[i],[k]:v};setForm({...form,progress_timeline:n})};return <Section title="Timeline tiến độ"><button type="button" onClick={add}><Plus size={16}/>Thêm mốc tiến độ</button><div className="v8Timeline">{list.map((x,i)=><article key={i}><CheckCircle2/><Fields><L t="Ngày cập nhật"><input type="date" value={x.date||''} onChange={e=>up(i,'date',e.target.value)}/></L><L t="Giai đoạn"><input value={x.stage||''} onChange={e=>up(i,'stage',e.target.value)}/></L><L t="Tỷ lệ hoàn thành"><input type="number" min="0" max="100" value={x.percent||0} onChange={e=>up(i,'percent',Number(e.target.value))}/></L><L t="Mô tả"><input value={x.description||''} onChange={e=>up(i,'description',e.target.value)}/></L></Fields></article>)}</div></Section>}
function MapTab({form,setForm}){return <Section title="Vị trí và bản đồ"><div className="v8SecurityNote"><MapPin/><div><b>Tọa độ dự án</b><span>Nhập tọa độ chính xác để hiển thị trên bản đồ và chuẩn bị lớp quy hoạch/rủi ro.</span></div></div><Fields><L t="Vĩ độ"><input value={form.latitude||''} onChange={e=>setForm({...form,latitude:e.target.value})}/></L><L t="Kinh độ"><input value={form.longitude||''} onChange={e=>setForm({...form,longitude:e.target.value})}/></L></Fields></Section>}
function AiTab({form,setForm}){const a=form.ai_profile||{};return <Section title="Dữ liệu dành cho AI"><Fields one>{[['strengths','Điểm mạnh'],['weaknesses','Điểm hạn chế'],['target_customer','Khách hàng phù hợp'],['keywords','Từ khóa tìm kiếm'],['faq','Câu hỏi thường gặp'],['source_notes','Nguồn dữ liệu AI được phép sử dụng']].map(([k,t])=><L key={k} t={t}><textarea rows="3" value={a[k]||''} onChange={e=>setForm({...form,ai_profile:{...a,[k]:e.target.value}})}/></L>)}</Fields><div className="v8SecurityNote"><ShieldCheck/><div><b>AI chỉ hỗ trợ</b><span>Mọi nội dung pháp lý, định giá và dữ liệu nhạy cảm phải được người có thẩm quyền kiểm duyệt trước khi công khai.</span></div></div></Section>}
function UploadCard({icon,title,accept,onUpload,hero}){const[file,setFile]=useState(null),[name,setName]=useState(""),[isHero,setHero]=useState(false);return <div className="v8UploadCard"><div className="v8UploadIcon">{icon}</div><b>{title}</b><input placeholder="Tiêu đề hiển thị" value={name} onChange={e=>setName(e.target.value)}/><label className="v8File"><UploadCloud size={16}/><span>{file?file.name:"Chọn tệp"}</span><input type="file" accept={accept} onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{hero&&<label className="v8MiniCheck"><input type="checkbox" checked={isHero} onChange={e=>setHero(e.target.checked)}/>Đặt làm ảnh hero</label>}<button type="button" disabled={!file} onClick={()=>{onUpload(file,name,isHero);setFile(null);setName("")}}>Tải lên</button></div>}
function Section({title,children}){return <div className="v8FormSection"><h3>{title}</h3>{children}</div>}
function Fields({children,one}){return <div className={`v8Fields ${one?'one':'two'}`}>{children}</div>}
function L({t,children,wide}){return <label className={wide?'wide':''}>{t}{children}</label>}
